#version: '3.8'
services:

  # PHP Service container
  laravel_app:
      platform: linux/amd64
      build:
          args:
              user: laravel_user
              uid: 1000
          context: .
          dockerfile: ./dockerfile
      image: laravel_app_image
      container_name: laravel_app
      restart: unless-stopped
      depends_on:
          -   db_mysql
      working_dir: /var/www
      volumes:
          -   ./:/var/www
      networks:
          - app_network
  #nginx service
  laravel_webserver:
      platform: linux/amd64
      image: nginx:alpine
      container_name: laravel_webserver_container
      restart: unless-stopped
      ports:
          - "6162:80"
      depends_on:
          -   laravel_app
      volumes:
          -   ./:/var/www
          - ./docker-compose/nginx/:/etc/nginx/conf.d
      networks:
          - app_network
  #mysql service
  db_mysql:
      platform: linux/amd64
      image: mysql:5.7.22
      container_name: db_mysql
      restart: unless-stopped
      ports:
          - "3337:3306"
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: password
      volumes:
          -   laravel_mysql_data:/var/lib/mysql
      networks:
          - app_network
  php_myadmin:
      image: phpmyadmin:5.2.1-apache
      container_name: php_myadmin
      restart: unless-stopped
      ports:
          -   "8383:80"
      environment:
          PMA_HOST: db_mysql
          PMA_PORT: 3306
          PMA_USER: root
          PMA_PASSWORD: password
      depends_on:
          -   db_mysql
      networks:
          - app_network
  redis:
      image: redis:7.2-alpine
      container_name: redis
      ports:
          -   "7379:6379"
      networks:
          - app_network
  # Jenkins service
  jenkins:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
    restart: unless-stopped
    networks:
      - app_network

volumes:
  laravel_mysql_data:
      driver: local
  jenkins_home:

networks:
  app_network:
      driver: bridge